version: "3"

services:
  api:
    build: ./django/
    env_file: .env
    command: ["/code/docker-entrypoint.sh"]
    environment:
      DEBUG: "true"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - "./django:/code"

  web:
    build: ./angular
    command: ["npm", "start"]
    ports:
      - "4200:4200"
    volumes:
      - "./angular:/app"
    depends_on:
      - api

  db:
    image: postgres:13
    env_file: .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: karite
      POSTGRES_PASSWORD: cosmeticroot1957
      POSTGRES_DB: cosmetic_republic
      POSTGRES_DB_HOST: db
      POSTGRES_PORT: 5432
